### ISSUE TITLE
Compatibility for Confluence version 7.3.1

### ISSUE THREAD

**Issue by hkut** [structurizr/atlassian-confluence#3]

**Comment by simonbrowndotje** [comment]
The macro should be compatible with 7.3.1 -> https://marketplace.atlassian.com/apps/1215547/structurizr-for-confluence-server?hosting=server&tab=versions

Are you seeing some problems?

**Comment by hkut** [comment]
Yes, it doesn't start after installing. We rebuilt it. I don't have rights to repo so you can find it here.

https://github.com/hkut/structurizr

**Comment by hkut** [comment]
Issue was related to change in Atlassian Spring Scanner:
https://bitbucket.org/atlassian/atlassian-spring-scanner/src/master/

**Comment by simonbrowndotje** [comment]
Thanks, I've recompiled the macros and published v2.1.0 to the Atlassian Marketplace.
