### ISSUE TITLE
Security Self-Assessment Program

### ISSUE THREAD

**Issue by mac89** [structurizr/atlassian-confluence#6]
Would you guys mind doing the Atlassian Security Self-Assessment Program here; https://developer.atlassian.com/platform/marketplace/security-self-assessment-program/

We'd like to use your tool but can't use it with Confluence, because of security audit troubles it would cause without that assessment.
It would be greatly appreciated!

**Comment by simonbrowndotje** [comment]
This Confluence macro is provided free and as-is - you're free to fork the repo and build your own version for deployment into your Confluence instance. From a security perspective, all this macro does is generate a HTML iframe ... https://github.com/structurizr/atlassian-confluence-server/blob/master/src/main/java/com/structurizr/confluence/StructurizrWorkspaceEmbedMacro.java#L12

**Comment by mac89** [comment]
I understand it's a safe enough solution. Management needs to have a more official record, however.
If you don't want to bother with the assessment, I understand. I'll take your advice and fork this repo.
